services:
  hjem:
    build: .
    container_name: hjem
    ports:
      - "3002:3002"
    environment:
      HOST: 0.0.0.0
      PORT: 3002
      NITRO_HOST: 0.0.0.0
      NITRO_PORT: 3002
      NODE_ENV: production
    restart: unless-stopped
    volumes:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:3002"]
      interval: 30s
      timeout: 10s
      retries: 3
